apiVersion: v1
kind: Namespace
metadata:
  name: cob-service
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # <--- FONDAMENTALE: Disabilita classi automatiche
  nfs:
    server: 192.168.15.9
    path: /srv/nfs/mongo_shared_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: cob-service
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # <--- FONDAMENTALE: Deve combaciare col PV
  resources:
    requests:
      storage: 5Gi